import type { Metadata } from 'next';
import './globals.css';

import { Inter } from 'next/font/google';
import { ToastProvider } from '@/components/ui/use-toast';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
      <html lang="ja" className={inter.variable}>
      <body>
        {/* ここでグローバルにトースト機能を注入 */}
        <ToastProvider>
          {children}
        </ToastProvider>
      </body>

    </html>
  );
}